"0814 川普豪宅為什麼被FBI闖入、歐洲能源現狀、經濟學人fat shaming？" = "0814 川普豪宅為什麼被FBI闖入、歐洲能源現狀是怎樣、經濟學人fat shaming？"
"PELOSI ARRIVES in TAIWAN, We talk to REAL People, REAL Thoughts" = "HOT TAKE: What do TAIWANESE really THINK about NANCY PELOSI'S visit? (English)"
"越戰美國大兵有嚴重的用藥問題、讀書會：同情者 CH 2" = "讀書會：同情者 CH 2 越戰美國大兵有嚴重的用藥問題"
"0626 拜登想跟中國和好？ 澳洲新政府想跟中國破冰、荷花邊的威力" = "0626 拜登想跟中國和好？ 澳洲新政府想跟中國破冰、荷葉邊的威力"
"0619 醒來了的AI、汽車保險有理賠性病嗎、推薦劇：聽話的孩子：邪教的禱告與服從" = "0619 醒來了的AI、汽車保險有理賠HPV嗎、推薦劇：聽話的孩子：邪教的禱告與服從"
"女演員的互相傷害 觀眾在旁吃瓜 feat @酸酸脫口秀 @許乃涵 涵冷娜" = "女演員的互相傷害 觀眾在旁吃瓜 feat 酸酸 and 許乃涵 涵冷娜"
"0529 凱莉錄嘻哈、美國德州小學槍擊事件、新疆警察檔案、推薦電影：捍衛戰士：獨行俠" = "0529 凱莉錄嘻哈、美國德州小學槍擊事件、新疆警察檔案、推薦電影《捍衛戰士：獨行俠》"
"喜劇演員開喜劇俱樂部是悲劇的開始嗎？ 笑友會的無情工商 @黃豪平 @微笑丹尼的喜劇頻道" = "喜劇演員開喜劇俱樂部是悲劇的開始嗎？ 笑友會的無情工商 ft. 黃豪平, 微笑丹尼"
"The KK Show - #129 揭發聯合國的記者 - Naomi O’Leary (有CC字幕)⏐The Reporter Who EXPOSED the United Nations" = "The KK Show - #129 揭發聯合國的記者 - Naomi O’Leary"
"『Clubhouse特別企劃』歡迎被封城的聽眾來聊天" = "『Clubhouse特別企劃』與在中國封城的聽眾聊天"
"閒聊 #威爾史密斯 巴掌事件 ft. @酸酸脫口秀" = "閒聊 #威爾史密斯 巴掌事件 ft. 酸酸"
"The KK Show - #126 長生不老的科學 - 許翱麟教授" = "The KK Show - #126 長壽的秘密 - 許翱麟教授"
"0327 俄國股市大漲但是通膨漲更多、泰國將禁止用虛擬貨幣支付、推薦Youtube： @Will Tennyson" = "0327 俄國股市大漲但是通膨漲更多、泰國將禁止用虛擬貨幣支付、推薦Youtube： Will Tennyson"
"The KK Show - #124 杜汶澤 @杜汶澤喱騷 Chapman To's Lateshow" = "The KK Show - #123 杜汶澤 Chapman"
"讀書會： Fat Leonard 完結，關心一下隔離中的 @敏迪選讀" = "讀書會： Fat Leonard 完結，關心一下隔離中的Mindy"
"美國海軍出賣台灣機密為了滿足私慾，讀書會：Fat Leonard #04" = "美國海軍出賣台灣機密為了滿足私慾，讀書會：Fat Leonard Ch 4"
"The KK Show - #122 匿名者 - 蕭東意 @嚎哮排演HaoxHsiaoTroupe" = "The KK Show - #122 匿名者 蕭東意"
"第一次在秘密基地錄音、小看女人會出大事 | 讀書會：Fat Leonard #03" = "第一次在秘密基地錄音、小看女人會出大事 | 讀書會：Fat Leonard Ch 3"
"The KK Show - #121 運動歸運動 政治歸政治(?) - 人渣文本" = "The KK Show - #121 運動歸運動 政治歸政治？ 人渣文本"
"The KK Show - #120 時代革命導演：周冠威" = "The KK Show - #120 時代革命導演 - 周冠威"
"The KK Show - #119 @黃大謙" = "The KK Show - #119 黃大謙"
"0206 #谷愛凌 是超級間諜？ 紐西蘭爲什麽要開放旅游了？ 閒聊Joe Rogan 後續 推薦電影:偶然與想像" = "0206 #谷愛凌 是超級間諜？ 紐西蘭爲什麽要開放旅遊了？ 閒聊Joe Rogan 後續 推薦電影:偶然與想像"
"林獻堂的兒子們怎麽有辦法跟老爸旅游這麽久不發瘋？ 讀書會：林獻堂環球遊記 End" = "林獻堂的兒子們怎麽有辦法跟老爸旅遊這麽久不發瘋？ 讀書會：林獻堂環球遊記 End"
"The KK Show - #117 @呱吉" = "The KK Show - #117 呱吉"
"The KK Show - #115 與自己的奶和解 - @泥泥學姐Janie" = "The KK Show - #115 與自己的奶和解 - 泥泥學姐"
"0109 凱莉是真五迷、哈薩克暴動 俄國支援、教宗譴責不生小孩的人、推薦：Don’t Look Up, 疫年記西藏" = "0109 凱莉是真五迷、哈薩克暴動 俄國支援、教宗譴責不生小孩的人、推薦書：疫年記西藏"
"【百靈果】直接槓上 #五月天 ！自家小編打工竟然被翻手機？！" = "【百靈果】直接槓上五月天！自家小編打工竟然被翻手機？！"
"1212 教練帶辣妹去教人生道理、中國公務員被砍薪 連獎金都要交回去、蘋果跟中國的秘密協議、推薦： Youtube 頻道 @Colin and Samir" = "1212 教練帶辣妹來大學教球員人生道理、中國公務員被砍薪 連獎金都要交回去、蘋果跟中國的秘密協議、推薦： Youtube 頻道 @Colin and Samir"
