["KK_Show"]
inclusive = ["KK Show"]
exclusive = []
number = 1

["百靈果之友"]
inclusive = ["百靈果之友"]
exclusive = []
number = 1

["樂樂法利"]
inclusive = ["樂樂法利"]
exclusive = []
number = 1

["陳大天"]
inclusive = ["陳大天"]
exclusive = []
number = 1

["ChinaMac"]
inclusive = ["China Mac"]
exclusive = []
number = 1

["小歐"]
inclusive = ["小歐"]
exclusive = []
number = 1

[Jay]
inclusive = ["Jay"]
exclusive = []
number = 1

["王彩樺"]
inclusive = ["王彩樺"]
exclusive = []
number = 1

["吳品瑜"]
inclusive = ["吳品瑜"]
exclusive = []
number = 1

["台南人劇團"]
inclusive = ["台南人劇團"]
exclusive = []
number = 1

["陳零九"]
inclusive = ["陳零九"]
exclusive = []
number = 1

["吳淡如"]
inclusive = ["吳淡如"]
exclusive = []
number = 1

["楊杰凱"]
inclusive = ["楊杰凱"]
exclusive = []
number = 1

["Naomi_O’Leary"]
inclusive = ["Naomi O’Leary"]
exclusive = []
number = 1

[Kevin]
inclusive = ["Kevin"]
exclusive = ["百靈果NEWS"]
number = 1

["許翱麟"]
inclusive = ["許翱麟"]
exclusive = []
number = 1

["陳秋實"]
inclusive = ["陳秋實"]
exclusive = []
number = 1

["Chapman杜汶澤"]
inclusive = ["Chapman","杜汶澤"]
exclusive = []
number = 1

["蕭東意"]
inclusive = ["蕭東意"]
exclusive = []
number = 1

["人渣文本"]
inclusive = ["人渣文本"]
exclusive = []
number = 1

["周冠威"]
inclusive = ["周冠威"]
exclusive = []
number = 1

["黃大謙"]
inclusive = ["黃大謙"]
exclusive = []
number = 1

["妍霏"]
inclusive = ["妍霏"]
exclusive = []
number = 1

["學仁"]
inclusive = ["學仁"]
exclusive = []
number = 1

[Xin]
inclusive = ["Xin"]
exclusive = []
number = 1

["泥泥學姐"]
inclusive = ["泥泥學姐"]
exclusive = []
number = 1

["阮鳳儀"]
inclusive = ["阮鳳儀"]
exclusive = []
number = 1

["李四端"]
inclusive = ["李四端"]
exclusive = ["跟李四端道歉"]
number = 1

[Social]
inclusive = ["Social"]
exclusive = []
number = 1

[JC]
inclusive = ["JC"]
exclusive = []
number = 1

["林昶佐"]
inclusive = ["林昶佐"]
exclusive = []
number = 1

["吳怡農"]
inclusive = ["吳怡農"]
exclusive = []
number = 1

["美國台灣觀測站"]
inclusive = ["美國台灣觀測站"]
exclusive = []
number = 1

["Kimberley陳芳語"]
inclusive = ["Kimberley","陳芳語"]
exclusive = []
number = 1

["社畜"]
inclusive = ["社畜"]
exclusive = []
number = 1

["汪怡昕"]
inclusive = ["汪怡昕"]
exclusive = []
number = 1

["老K"]
inclusive = ["老K"]
exclusive = []
number = 1

["黃秋生"]
inclusive = ["黃秋生"]
exclusive = []
number = 1

["龍哥"]
inclusive = ["龍哥"]
exclusive = []
number = 1

["林榮基"]
inclusive = ["林榮基"]
exclusive = []
number = 1

["東冬侯溫"]
inclusive = ["東冬侯溫"]
exclusive = []
number = 1

["陳念琴"]
inclusive = ["陳念琴"]
exclusive = []
number = 1

[Neil]
inclusive = ["Neil"]
exclusive = []
number = 1

["盧卡斯@BBK_Networ"]
inclusive = ["盧卡斯","BBK Network"]
exclusive = []
number = 1

[Jack]
inclusive = ["Jack"]
exclusive = []
number = 1

["瑞典劉先生"]
inclusive = ["瑞典劉先生"]
exclusive = []
number = 1

["Byun秉昀"]
inclusive = ["Byun","秉昀"]
exclusive = []
number = 1

["李有宜"]
inclusive = ["李有宜"]
exclusive = []
number = 1

["桃子A1J"]
inclusive = ["桃子A1J"]
exclusive = []
number = 1

["張賢龢博士"]
inclusive = ["張賢龢"]
exclusive = []
number = 1

["娃娃"]
inclusive = ["娃娃"]
exclusive = []
number = 1

["高智雄醫檢師"]
inclusive = ["高智雄"]
exclusive = []
number = 1

["微笑丹尼"]
inclusive = ["微笑丹尼"]
exclusive = []
number = 1

["葉丙成"]
inclusive = ["葉丙成"]
exclusive = []
number = 1

["Dr.LeanneWu"]
inclusive = ["Leanne Wu"]
exclusive = []
number = 1

["Dr.JustinYang"]
inclusive = ["Justin Yang"]
exclusive = []
number = 1

["單信瑜教授"]
inclusive = ["單信瑜"]
exclusive = []
number = 1

["陳耀昌醫師"]
inclusive = ["陳耀昌"]
exclusive = []
number = 1

["布拉瑞揚@布拉瑞揚舞團"]
inclusive = ["布拉瑞揚"]
exclusive = []
number = 1

["石巴朝"]
inclusive = ["石巴朝"]
exclusive = []
number = 1

["蔣萬安"]
inclusive = ["蔣萬安"]
exclusive = []
number = 1

["范雲"]
inclusive = ["范雲"]
exclusive = []
number = 1

[IORG]
inclusive = ["IORG"]
exclusive = []
number = 1

["李律"]
inclusive = ["李律"]
exclusive = []
number = 1

["阿拉斯"]
inclusive = ["阿拉斯"]
exclusive = []
number = 1

["葉耀元教授"]
inclusive = ["葉耀元"]
exclusive = []
number = 1

["孫翠鳳"]
inclusive = ["孫翠鳳"]
exclusive = []
number = 1

[Vasilisa]
inclusive = ["Vasilisa"]
exclusive = []
number = 1

["LukeMartin"]
inclusive = ["Luke Martin"]
exclusive = []
number = 1

["陳小雀教授"]
inclusive = ["陳小雀"]
exclusive = []
number = 1

["SamsonEllis"]
inclusive = ["Samson Ellis"]
exclusive = []
number = 1

["博恩"]
inclusive = ["博恩"]
exclusive = ["老K","賀瓏"]
number = 1

["張五岳"]
inclusive = ["張五岳"]
exclusive = []
number = 1

["大可愛"]
inclusive = ["大可愛"]
exclusive = []
number = 1

[Chiels]
inclusive = ["Chiels","劉董"]
exclusive = []
number = 1

[Mego]
inclusive = ["Mego"]
exclusive = []
number = 1

["珂拉琪Collage"]
inclusive = ["珂拉琪Collage"]
exclusive = []
number = 1

[Nick]
inclusive = ["Nick"]
exclusive = []
number = 1

["黃逸豪"]
inclusive = ["黃逸豪"]
exclusive = []
number = 1

["李淳"]
inclusive = ["李淳"]
exclusive = []
number = 1

["唐綺陽"]
inclusive = ["唐綺陽"]
exclusive = []
number = 1

["東區德"]
inclusive = ["東區德"]
exclusive = []
number = 1

["小潘"]
inclusive = ["小潘"]
exclusive = []
number = 1

["寶拉"]
inclusive = ["寶拉"]
exclusive = []
number = 1

["于北辰"]
inclusive = ["于北辰"]
exclusive = []
number = 1

["志祺@志祺七七"]
inclusive = ["志祺","志祺七七"]
exclusive = []
number = 1

["阿滴"]
inclusive = ["阿滴"]
exclusive = []
number = 1

["林智堅"]
inclusive = ["林智堅"]
exclusive = []
number = 1

[Firstory]
inclusive = ["Firstory"]
exclusive = []
number = 1

["真蓉"]
inclusive = ["真蓉"]
exclusive = []
number = 1

["Jason劉致昕@報導者"]
inclusive = ["Jason","致昕"]
exclusive = []
number = 1

["印度尤"]
inclusive = ["印度尤"]
exclusive = []
number = 1

["EstherChen"]
inclusive = ["Esther Chen"]
exclusive = []
number = 1

["台灣通勤第一品牌"]
inclusive = ["台灣通勤第一品牌"]
exclusive = ["推薦Podcast"]
number = 1

["陳沂"]
inclusive = ["陳沂"]
exclusive = []
number = 1

[Joeman]
inclusive = ["Joeman"]
exclusive = []
number = 1

["烏烏醫生"]
inclusive = ["烏烏醫生"]
exclusive = []
number = 1

["陳柏惟"]
inclusive = ["陳柏惟"]
exclusive = []
number = 1

["黑嘉嘉"]
inclusive = ["黑嘉嘉"]
exclusive = []
number = 1

["沈伯洋（助理）教授"]
inclusive = ["沈伯洋"]
exclusive = []
number = 1

["趙哥"]
inclusive = ["趙哥"]
exclusive = []
number = 1

["Hito大聯盟"]
inclusive = ["Hito大聯盟"]
exclusive = []
number = 1

["法律白話文"]
inclusive = ["法律白話文"]
exclusive = []
number = 1

["簡少年"]
inclusive = ["簡少年"]
exclusive = []
number = 1

["邱grr"]
inclusive = ["邱grr","邱Grrr"]
exclusive = []
number = 1

["妍言"]
inclusive = ["妍言"]
exclusive = []
number = 1

["呱吉"]
inclusive = ["呱吉"]
exclusive = ["0516"]
number = 1

[Jim]
inclusive = ["Jim"]
exclusive = []
number = 1

["Pom咩"]
inclusive = ["Pom咩"]
exclusive = []
number = 1

["莉婷"]
inclusive = ["莉婷"]
exclusive = []
number = 1

["股癌"]
inclusive = ["股癌"]
exclusive = ["推薦Podcast"]
number = 1

[Niki]
inclusive = ["Niki"]
exclusive = []
number = 1

["酸酸"]
inclusive = ["酸酸"]
exclusive = []
number = 1

["涵冷娜"]
inclusive = ["許乃涵","涵冷娜"]
exclusive = []
number = 1

[Angeli]
inclusive = ["Angeli"]
exclusive = []
number = 1

[Feyza]
inclusive = ["Feyza"]
exclusive = []
number = 1

["龍龍"]
inclusive = ["龍龍"]
exclusive = []
number = 1

[Howard]
inclusive = ["Howard"]
exclusive = []
number = 1

[Ivan]
inclusive = ["Ivan"]
exclusive = []
number = 1

[Wolf]
inclusive = ["Wolf"]
exclusive = []
number = 1

["么么"]
inclusive = ["么么"]
exclusive = []
number = 1

["怡岑"]
inclusive = ["怡岑"]
exclusive = []
number = 1

["阿爆"]
inclusive = ["阿爆"]
exclusive = ["阿爆演唱會"]
number = 1

[Angel]
inclusive = ["Angel"]
exclusive = ["Angeli"]
number = 1

["顧立楷"]
inclusive = ["顧立楷"]
exclusive = []
number = 1

["范琪斐"]
inclusive = ["范琪斐"]
exclusive = []
number = 1

["賀瓏"]
inclusive = ["賀瓏"]
exclusive = []
number = 1

["ShaoYong"]
inclusive = ["Shao Yong"]
exclusive = []
number = 1

["歐馬克"]
inclusive = ["歐馬克"]
exclusive = []
number = 1

["艾董"]
inclusive = ["艾董"]
exclusive = []
number = 1

["黃豪平"]
inclusive = ["黃豪平"]
exclusive = []
number = 1

["馬力歐"]
inclusive = ["馬力歐"]
exclusive = []
number = 1

["TimChen"]
inclusive = ["Tim Chen"]
exclusive = []
number = 1

[Mario]
inclusive = ["Mario"]
exclusive = []
number = 1
