"什麼！魔羯座也會哭？12星座，想哭的時候" = "extra"
"12星座想哭的時候💦 #唐綺陽xVogue" = "extra"
"3/18-3/24｜星座運勢週報｜唐綺陽" = "extra"
"3/25-3/31｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】感情不順都是肝的問題？ft.簡少年" = "extra"
"各位小心肝，請小心肝。" = "extra"
"唐綺陽直播｜水逆的四月｜四月運勢" = "extra"
"4/1-4/7｜星座運勢週報｜唐綺陽" = "extra"
"今早6點正式水逆啦！#占星 #水逆 #星座" = "extra"
"4/8-4/14｜星座運勢週報｜唐綺陽" = "extra"
"【風象星座篇】水逆的四月 #四月運勢" = "extra"
"【火象星座篇】水逆的四月 #四月運勢" = "extra"
"【水象星座篇】水逆的四月 #四月運勢" = "extra"
"【土象星座篇】水逆的四月 #四月運勢" = "extra"
"焦慮代表你靈魂挺有野心的🎧EP310 #30歲 #長大 #壓力 #焦慮" = "extra"
