"【週二夜現場】會說唱的美國反賊 - 樂樂法利 @LeLe Farley" = "extra592"
"【週二夜現場】樂樂法利來台灣！ @LeLe Farley" = "extra592"
"掉到波蘭的飛彈到底是誰的？好大的一盤棋啊 #shorts" = "extra593"
"#Clips 川普宣布選總統 民主黨雙手歡迎？| 百靈果News" = "extra593"
"#Clips 波蘭飛彈事件要謹慎對待 | 百靈果News" = "extra593"
"#Clips 習近平當全世界的面教訓加拿大 | 百靈果News" = "extra593"
"The KK Show - #162 來福好事 - 龍哥" = "time594"
"習近平把加拿大總理當孫子訓話，旁邊翻譯都驚呆了 🤯#百靈果news #百靈果" = "extra597"
"#Clips 台中人聽到這個一定笑？ | The KK Show - #162 散盡家財做喜劇 - 龍哥" = "extra594"
"#Clips 太年輕學喜劇會壞掉？ | The KK Show - #162 散盡家財做喜劇 - 龍哥" = "extra594"
"￼如何￼ 3秒內跟台中人變成好朋友￼ #shorts" = "extra594"
"【週二夜現場】喬瑟夫 & 博恩 @Stand up, Brian! 博恩站起來！ @喬瑟夫 ChillSeph" = "time595"
"博恩的鳥笑話 #shorts" = "extra595"
"Last night hundred of people gathered in Shanghai to call for RESIGNATION of Xi Jinping 上海聚集抗議" = "extra596"
"博恩覺得賀瓏是冗員？？#shorts" = "extra595"
"11/27 上海法租界警察抓人 （螢幕錄製）" = "extra596"
"The KK Show - #161 @喬瑟夫 ChillSeph" = "time591"
"#Clips 再怎麼窮還是要待在劇團，什麼是漫才？ | The KK Show - #161 @喬瑟夫 ChillSeph" = "extra591"
"#Clips 自己個性上特立獨行跟小時候的經驗沒關係 | The KK Show - #161 @喬瑟夫 ChillSeph" = "extra591"
"#Clips 小時候的喬瑟夫沒有被性侵| The KK Show - #161 @喬瑟夫 ChillSeph" = "extra591"
"The KK Show - #00 一切的起源 - Podcast的馬力歐" = "time120"
"The KK Show - #01 國合會技術團 - Mario" = "time113"
"The KK Show - #02 香港脫口秀演員 - Tim Chen" = "time118"
"醫師與蘭嶼人面對死亡的態度｜KK Show - #149 離島醫生 - 黃京葦醫師" = "extra558"
"剛到蘭嶼的文化衝擊｜KK Show - #149 離島醫生 - 黃京葦醫師" = "extra558"
"打不過中國怎麼辦｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra562"
"希望捐出來的30億要怎麼用｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra562"
"為什麼要捐30億？｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra562"
"講不到兩年辦專場被別人靠北？｜KK Show - #151 巴斯" = "extra564"
"結婚多年後 凱莉重新認識老公｜KK Show - #151 巴斯" = "extra564"
"五燈獎是在石器時代前還是之後？｜The KK Show - #152 #趙詠華＆#林俊逸" = "extra567"
"歌手會被騙去飯局發展事業第二春？｜The KK Show - #152 趙詠華＆林俊逸" = "extra567"
"(CC字幕) The KK Show - #153 逃出中國 - Michael Smith" = "time570"
"逃出上海 Escape Shanghai!｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra570"
"有外媒相信中國的謊言？ Western media bought into Chinese LIES about XINJIANG｜ The KK Show - #153 Michael Smith" = "extra570"
"Escape Shanghai! 逃出上海 ｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra570"
"Western media bought into Chinese LIES about XINJIANG 有外媒相信中國的謊言？ ｜ The KK Show - #153 Michael Smith" = "extra570"
"(Complete Version)(CC字幕) The KK Show - #153 逃出中國 - Michael Smith" = "extra570"
"#clips Western media bought into Chinese LIES about XINJIANG 有外媒相信中國的謊言？ ｜ The KK Show Michael Smith" = "extra570"
"#Clips Escape Shanghai! 逃出上海 ｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra570"
"The KK Show - #154 好機車-嗩吶 @好機車" = "time573"
"Andrew Tate到底是誰？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra573"
"#Clips Andrew Tate到底是誰？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra573"
"#Clips 戰狼電影幕後秘辛、被解放軍圍起來？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra573"
"#Clips 離鄉背井結果被當成白猴子，後來反轉人生！ ｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra576"
"#Clips 台灣要留住外來人才法規需要更友善｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra576"
"#Clips 台灣流行樂壇沒落的原因 ｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra576"
"#Clips 離鄉背井在中國被當成白猴子｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra576"
"#Clips 以前成功的那套在新媒體不一定吃得開｜ The KK Show - #156 吳念真" = "extra579"
"#Clips 政治歸政治 藝術歸藝術是屁話｜ The KK Show - #156 吳念真" = "extra579"
"#Clips 舞台是烏托邦的展現｜ The KK Show - #156 吳念真" = "extra579"
"#Clips 館長電商經營甘苦談 | The KK Show - #157 館長" = "extra583"
"#Clips 疫情對健身產業的影響 | The KK Show - #157 館長" = "extra583"
"#Clips 除了掃地 除草，軍人可以做更多 | The KK Show - #157 館長" = "extra583"
"The KK Show - #158 與鯨魚游泳的男人 - 剛哥" = "time586"
"#Clips 在海中\"淺\"出全新的世界 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra586"
"#Clips 看美女水下美照 不如看鯨魚 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra586"
"#Clips 在海中\"潛\"出全新的世界 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra586"
"#Clips 看辣妹水下美照 不如看鯨魚 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra586"
"#Clips 擦槍走火的論文門事件內幕 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra587"
"#Clips 投票率創下30年來新低 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra587"
"The KK Show - #160 民進黨新竹縣候選人 - 周江杰" = "time588"
"#Clips 尼采認為的 道德枷鎖？ ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra587"
"#Clips 今年投票率將創下30年來新低 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra587"
"#Clips 新竹縣的年輕人需要什麼？ | The KK Show - #160 新竹縣長候選人 - 周江杰" = "extra588"
"#Clips 沒有資源要怎麼選艱困選區？ | The KK Show - #160 新竹縣長候選人 - 周江杰" = "extra588"
