# Special

["百靈果到處跑"]
inclusive = ["老闆去新竹向員工道歉","John Oliver 觀後感"]
exclusive = []
category = ["#節目系列","暫代讀書會"]

["百靈果之友"]
inclusive = ["百靈果之友"]
exclusive = []
category = ["#節目系列","暫代讀書會"]

["免費教你如何做 Podcast"]
inclusive = ["免費教你如何做Podcast"]
exclusive = []
category = ["#節目系列","暫代讀書會"]

["八角籠"]
inclusive = ["八角籠"]
exclusive = []
category = ["#節目系列","暫代讀書會"]

["Clubhouse 直播"]
inclusive = ["八角籠直播","海外連線","『Clubhouse特別企劃』","直播聊這幾天在中國"]
exclusive = []
category = ["#節目系列","暫代讀書會"]
