"#節目系列" = ["百靈果 NEWS", "百靈果 Bonus", "KK Show", "Live Podcast", "週二夜現場", "THE STIR", "讀書會", "隱藏版 KK Show", "暫代讀書會", "百靈果到處跑", "百靈果之友", "免費教你如何做 Podcast", "八角籠", "Clubhouse 企劃"]
"讀書會" = ["八尺門的辯護人", "同情者", "柏青哥", "Fat Leonard", "林獻堂環球遊記", "吃佛", "宮前町九十番", "CIA洗腦計畫", "蚵仔煎的身世", "傀儡花", "毒家企業", "宋氏三姊妹", "The Room Where It Happened by John Bolton", "Rage by Bob Woodward", "浪淘沙", "戰裡的夏里特", "鴻：三代中國女人", "This American Life", "核爆家園", "陳澄波密碼", "以母之名"]
"暫代讀書會" = ["百靈果到處跑", "百靈果之友", "免費教你如何做 Podcast", "八角籠", "Clubhouse 企劃"]
"#事件備註" = ["日本遶境", "裴洛西訪台事件", "國傳司事件", "紐時集資事件", "五月天事件"]
"喜劇演員" = ["樂樂法利", "陳大天", "小歐", "老K", "妍霏", "學仁", "Social", "歐馬克", "微笑丹尼", "博恩", "大可愛", "權樂", "巴斯", "黃逸豪", "艾董", "黃豪平", "Tim Chen", "東區德", "阿秋", "賀瓏", "么么", "怡岑", "酸酸", "涵冷娜", "Esther Chen", "呱吉", "Jim", "龍龍", "蕭東意"]
Youtuber = ["樂樂法利", "小歐", "微笑丹尼", "黃豪平", "賀瓏", "酸酸", "呱吉", "Jim", "龍龍", "范琪斐", "志祺 @志祺七七", "好和弦 @NiceChord", "阿滴", "Joeman", "黃大謙", "China Mac", "邱 grr", "泥泥學姐", "盧卡斯 @BBK Networ", "歷史哥", "阿拉斯", "巴大雄 @東南美娛樂"]
"藝人" = ["陳大天", "黃豪平", "王彩樺", "趙詠華", "林俊逸", "陳沂"]
"企業家" = ["Social", "呱吉", "志祺 @志祺七七", "阿滴", "Joeman", "邱 grr", "Chapman 杜汶澤", "葉丙成教授", "曹興誠", "Jay", "顧立楷", "林榮基"]
Podcaster = ["歐馬克", "酸酸", "范琪斐", "敏迪 @敏迪選讀", "志祺 @志祺七七", "好和弦 @NiceChord", "趙詠華", "林俊逸", "劉珞亦 @法律白話文", "楊貴智 @法律白話文", "唐綺陽", "簡少年", "台灣通勤第一品牌", "股癌", "瑞典劉先生", "Firstory", "馬力歐", "吳淡如", "Howard"]
"廣播人" = ["歐馬克", "黃豪平", "李律", "邵大倫", "小潘", "寶拉", "吳淡如"]
"演員" = ["權樂", "涵冷娜", "Esther Chen", "Chapman 杜汶澤", "黃秋生", "蕭東意"]
"文藝" = ["權樂", "涵冷娜", "Esther Chen", "Chapman 杜汶澤", "黃秋生", "台南人劇團", "蕭東意", "布拉瑞揚 @布拉瑞揚舞團", "孫翠鳳", "真蓉"]
"專業人士" = ["巴斯", "劉珞亦 @法律白話文", "楊貴智 @法律白話文", "Howard", "楊杰凱", "黑嘉嘉"]
"工程師" = ["巴斯"]
"魔術師" = ["巴斯", "黃豪平"]
"政治人物" = ["呱吉", "陳柏惟", "林昶佐", "吳怡農", "李有宜", "蔣萬安", "范雲", "于北辰", "林智堅", "郭書成"]
"時事" = ["范琪斐", "敏迪 @敏迪選讀", "瑞典劉先生", "陳秋實", "Jason 劉致昕 @報導者", "Byun 秉昀", "Samson Ellis", "Michael Smith", "吳品瑜", "印度尤", "Naomi O’Leary", "Kevin", "Mario", "黃京葦醫師", "烏烏醫生", "Chiels", "李淳", "Dr. Leanne Wu", "Dr. Justin Yang", "葉耀元教授", "陳小雀教授", "張賢龢博士", "單信瑜教授", "高智雄醫檢師", "美國台灣觀測站", "IORG", "沈伯洋（助理）教授", "張五岳", "Luke Martin"]
"音樂" = ["阿爆", "阿拉斯", "巴大雄 @東南美娛樂", "陳零九", "Kimberley陳芳語", "王彩樺", "趙詠華", "林俊逸", "桃子 A1J", "珂拉琪 Collage", "林昶佐"]
"原住民" = ["阿爆", "阿拉斯", "巴大雄 @東南美娛樂", "黃京葦醫師", "陳念琴", "東冬侯溫"]
"朋友" = ["阿爆", "Howard", "Ivan", "Shao Yong", "趙哥", "陳沂", "Pom 咩"]
"色色" = ["社畜", "娃娃", "石巴朝", "Niki"]
"劇場" = ["台南人劇團", "蕭東意"]
"舞蹈" = ["布拉瑞揚 @布拉瑞揚舞團"]
"律師" = ["劉珞亦 @法律白話文", "楊貴智 @法律白話文"]
"導演" = ["周冠威", "阮鳳儀"]
"製作人" = ["汪怡昕", "龍哥", "Roger"]
"影視製作" = ["Mego", "Nick"]
"媒體人" = ["吳淡如", "李四端"]
"記者" = ["陳秋實", "Jason 劉致昕 @報導者", "Byun 秉昀", "Samson Ellis", "Michael Smith", "Naomi O’Leary", "莉婷"]
"醫學" = ["黃京葦醫師", "烏烏醫生", "陳耀昌醫師", "Chiels", "Dr. Leanne Wu", "Dr. Justin Yang", "高智雄醫檢師"]
"學者" = ["黃京葦醫師", "烏烏醫生", "許翱麟教授", "人渣文本", "陳耀昌醫師", "Chiels", "李淳", "Dr. Leanne Wu", "Dr. Justin Yang", "葉耀元教授", "陳小雀教授", "張賢龢博士", "葉丙成教授", "單信瑜教授", "高智雄醫檢師", "沈伯洋（助理）教授"]
"運動" = ["人渣文本", "莉婷", "陳念琴", "妍言", "Hito 大聯盟", "Jack"]
"作者" = ["陳耀昌醫師"]
"聽眾" = ["Xin", "JC", "Vasilisa", "Angeli", "Angel", "Feyza"]
"口譯員" = ["Howard"]
"專利師" = ["楊杰凱"]
"編輯" = ["Neil"]
"事實查核" = ["IORG", "沈伯洋（助理）教授"]
"來賓" = ["Wolf"]
