"百靈果 NEWS" = ["#節目系列"]
"百靈果 Bonus" = ["#節目系列"]
"KK Show" = ["#節目系列"]
"Live Podcast" = ["#節目系列"]
"週二夜現場" = ["#節目系列"]
"THE STIR" = ["#節目系列"]
"讀書會" = ["#節目系列"]
"同情者" = ["讀書會"]
"柏青哥" = ["讀書會"]
FatLeonard = ["讀書會"]
"林獻堂環球遊記" = ["讀書會"]
"吃佛" = ["讀書會"]
"宮前町九十番" = ["讀書會"]
"CIA洗腦計畫" = ["讀書會"]
"蚵仔煎的身世" = ["讀書會"]
"傀儡花" = ["讀書會"]
"毒家企業" = ["讀書會"]
"宋氏三姊妹" = ["讀書會"]
"The Room Where It Happened by John Bolton" = ["讀書會"]
"Rage by Bob Woodward" = ["讀書會"]
"浪淘沙" = ["讀書會"]
"戰裡的夏里特" = ["讀書會"]
"鴻：三代中國女人" = ["讀書會"]
"This American Life" = ["讀書會"]
"核爆家園" = ["讀書會"]
"陳澄波密碼" = ["讀書會"]
"以母之名" = ["讀書會"]
"隱藏版 KK Show" = ["#節目系列"]
"暫代讀書會" = ["#節目系列"]
"百靈果到處跑" = ["#節目系列", "暫代讀書會"]
"百靈果之友" = ["#節目系列", "暫代讀書會"]
"免費教你如何做Podcast" = ["#節目系列", "暫代讀書會"]
"八角籠" = ["#節目系列", "暫代讀書會"]
"Clubhouse企劃" = ["#節目系列", "暫代讀書會"]
"日本遶境" = ["#事件備註"]
"裴洛西訪台事件" = ["#事件備註"]
"國傳司事件" = ["#事件備註"]
"紐時集資事件" = ["#事件備註"]
"五月天事件" = ["#事件備註"]
"樂樂法利" = ["喜劇演員", "Youtuber"]
"陳大天" = ["喜劇演員", "藝人"]
"小歐" = ["喜劇演員", "Youtuber"]
"老K" = ["喜劇演員"]
"妍霏" = ["喜劇演員"]
"學仁" = ["喜劇演員"]
Social = ["喜劇演員", "企業家"]
"歐馬克" = ["Podcaster", "喜劇演員", "廣播人"]
"微笑丹尼" = ["喜劇演員", "Youtuber"]
"博恩" = ["喜劇演員"]
"大可愛" = ["喜劇演員"]
"權樂" = ["喜劇演員", "演員", "文藝"]
"巴斯" = ["喜劇演員", "專業人士", "工程師", "魔術師"]
"黃逸豪" = ["喜劇演員"]
"艾董" = ["喜劇演員"]
"黃豪平" = ["喜劇演員", "廣播人", "藝人", "Youtuber", "魔術師"]
TimChen = ["喜劇演員"]
"東區德" = ["喜劇演員"]
"阿秋" = ["喜劇演員"]
"賀瓏" = ["喜劇演員", "Youtuber"]
"么么" = ["喜劇演員"]
"怡岑" = ["喜劇演員"]
"酸酸" = ["喜劇演員", "Youtuber", "Podcaster"]
"涵冷娜" = ["喜劇演員", "演員", "文藝"]
EstherChen = ["喜劇演員", "演員", "文藝"]
"呱吉" = ["喜劇演員", "Youtuber", "政治人物", "企業家"]
Jim = ["喜劇演員", "Youtuber"]
"龍龍" = ["喜劇演員", "Youtuber"]
"范琪斐" = ["時事", "Youtuber", "Podcaster"]
"敏迪 @敏迪選讀" = ["時事", "Podcaster"]
"志祺 @志祺七七" = ["Youtuber", "Podcaster", "企業家"]
"好和弦 @NiceChord" = ["Youtuber", "Podcaster"]
"阿滴" = ["Youtuber", "企業家"]
Joeman = ["Youtuber", "企業家"]
"黃大謙" = ["Youtuber"]
ChinaMac = ["Youtuber"]
"邱grr" = ["Youtuber", "企業家"]
"泥泥學姐" = ["Youtuber"]
"盧卡斯 @BBK Networ" = ["Youtuber"]
"歷史哥" = ["Youtuber"]
"阿爆" = ["音樂", "原住民", "朋友"]
"阿拉斯" = ["Youtuber", "音樂", "原住民"]
"巴大雄 @東南美娛樂" = ["Youtuber", "音樂", "原住民"]
"社畜" = ["色色"]
"娃娃" = ["色色"]
"石巴朝" = ["色色"]
Niki = ["色色"]
"陳零九" = ["音樂"]
"Kimberley陳芳語" = ["音樂"]
"王彩樺" = ["藝人", "音樂"]
"桃子A1J" = ["音樂"]
"珂拉琪Collage" = ["音樂"]
"Chapman杜汶澤" = ["演員", "企業家", "文藝"]
"黃秋生" = ["演員", "文藝"]
"台南人劇團" = ["文藝", "劇場"]
"蕭東意" = ["文藝", "演員", "劇場", "喜劇演員"]
"布拉瑞揚 @布拉瑞揚舞團" = ["文藝", "舞蹈"]
"孫翠鳳" = ["文藝"]
"真蓉" = ["文藝"]
"劉珞亦 @法律白話文" = ["Podcaster", "專業人士", "律師"]
"楊貴智 @法律白話文" = ["Podcaster", "專業人士", "律師"]
"唐綺陽" = ["Podcaster"]
"簡少年" = ["Podcaster"]
"台灣通勤第一品牌" = ["Podcaster"]
"股癌" = ["Podcaster"]
"瑞典劉先生" = ["時事", "Podcaster"]
Firstory = ["Podcaster"]
"馬力歐" = ["Podcaster"]
"周冠威" = ["導演"]
"阮鳳儀" = ["導演"]
"汪怡昕" = ["製作人"]
"龍哥" = ["製作人"]
Roger = ["製作人"]
Mego = ["影視製作"]
Nick = ["影視製作"]
"李律" = ["廣播人"]
"邵大倫" = ["廣播人"]
"小潘" = ["廣播人"]
"寶拉" = ["廣播人"]
"吳淡如" = ["廣播人", "媒體人", "Podcaster"]
"李四端" = ["媒體人"]
"陳秋實" = ["時事", "記者"]
"Jason劉致昕 @報導者" = ["時事", "記者"]
"Byun秉昀" = ["時事", "記者"]
SamsonEllis = ["時事", "記者"]
"吳品瑜" = ["時事"]
"印度尤" = ["時事"]
"Naomi O’Leary" = ["時事", "記者"]
Kevin = ["時事"]
Mario = ["時事"]
"陳柏惟" = ["政治人物"]
"林昶佐" = ["政治人物", "音樂"]
"吳怡農" = ["政治人物"]
"李有宜" = ["政治人物"]
"蔣萬安" = ["政治人物"]
"范雲" = ["政治人物"]
"于北辰" = ["政治人物"]
"林智堅" = ["政治人物"]
"郭書成" = ["政治人物"]
"黃京葦醫師" = ["醫學", "學者", "時事", "原住民"]
"烏烏醫生" = ["醫學", "學者", "時事"]
"許翱麟教授" = ["學者"]
"人渣文本" = ["學者", "運動"]
"陳耀昌醫師" = ["醫學", "學者", "作者"]
Chiels = ["醫學", "學者", "時事"]
"李淳" = ["學者", "時事"]
"Dr.LeanneWu" = ["時事", "醫學", "學者"]
"Dr.JustinYang" = ["時事", "醫學", "學者"]
"葉耀元教授" = ["時事", "學者"]
"陳小雀教授" = ["時事", "學者"]
"張賢龢博士" = ["時事", "學者"]
"葉丙成教授" = ["學者", "企業家"]
"單信瑜教授" = ["時事", "學者"]
"高智雄醫檢師" = ["時事", "醫學", "學者"]
Xin = ["聽眾"]
JC = ["聽眾"]
Vasilisa = ["聽眾"]
Angeli = ["聽眾"]
Angel = ["聽眾"]
Feyza = ["聽眾"]
"莉婷" = ["記者", "運動"]
"陳念琴" = ["運動", "原住民"]
"妍言" = ["運動"]
"Hito大聯盟" = ["運動"]
Jack = ["運動"]
Howard = ["朋友", "Podcaster", "專業人士", "口譯員"]
Ivan = ["朋友"]
ShaoYong = ["朋友"]
"趙哥" = ["朋友"]
"陳沂" = ["朋友", "藝人"]
"楊杰凱" = ["專業人士", "專利師"]
"黑嘉嘉" = ["專業人士"]
"曹興誠" = ["企業家"]
Jay = ["企業家"]
"顧立楷" = ["企業家"]
"林榮基" = ["企業家"]
Neil = ["編輯"]
"美國台灣觀測站" = ["時事"]
IORG = ["時事", "事實查核"]
"沈伯洋（助理）教授" = ["時事", "事實查核", "學者"]
"張五岳" = ["時事"]
LukeMartin = ["時事"]
"東冬侯溫" = ["原住民"]
"Pom咩" = ["朋友"]
Wolf = ["來賓"]
