name: update podcast feed

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Running Script
        run: |
          pip install -r requirements.txt
          python act2-update.py
          python act3-merge.py
          python act4-annotate.py > filter.txt
          python act5-exportJS.py
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git commit -a -m "new date commit"
          git push origin master
