name: update podcast feed v3.4.0

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # runs-on: [self-hosted, linux, x64]
    # runs-on: [linux, x64]
    runs-on: ubuntu-latest
    outputs:
      git_status: ${{ steps.check.outputs.git_status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check py requirements
        run: |
          pip3 install -r requirements.txt
      - name: update rss feed source
        env:
          SPT_ID: ${{ secrets.spotify_client_id }}
          SPT_SC: ${{ secrets.spotify_client_secret }}
        run: |
          python3 secret.py --spotify_id "$SPT_ID" --spotify_secret "$SPT_SC"
          python3 update.py blg
          # python3 update.py exr
      - name: merge feed source
        run: |
          python3 merge.py blg
          # python3 merge.py exr
      - name: annotate feed with various info
        run: |
          python3 annotate.py blg > blg/filter.txt
          # python3 annotate.py exr > exr/filter.txt
      - name: export feed into js file
        run: |
          python3 export.py blg
          # python3 export.py exr
      - name: setup git config
        env:
          EMAIL: ${{ secrets.email }}
          KEY: ${{ secrets.key }}
        run: |
          git config user.name "RSS Update Bot"
          git config user.email "$EMAIL"
          # git config user.signingkey "$KEY"
      - name: check
        id: check_git_status
        run: |
          echo "git_status="`git status --porcelain`
          echo "git_status="`git status --porcelain` >> $GITHUB_OUTPUT
      - name: commit
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        run: |
          echo git_status: ${{ steps.check_git_status.outputs.git_status }}
          git add -A
          # git commit -S -m "update rss feed "`TZ='<UTC+8>-8' date +'%b_%d,_%Y_%H:%M:%S'`" [bot action]" && git push
          git commit -m "update rss feed "`TZ='<UTC+8>-8' date +'%b_%d,_%Y_%H:%M:%S'`" [bot action]" && git push
      - name: Echo
        run: |
          echo ${{ needs.build.outputs.git_status }}
      - name: Checkout
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Pages
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        id: deployment
        uses: actions/deploy-pages@v2
