name: update podcast feed v2.0.3

on:
  schedule:
    - cron: "5 * * * * "
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Running Script
        run: |
          pip install -r requirements.txt
          python3 act2-update.py
          python3 act3-merge.py
          python3 act4-annotate.py > filter.txt
          python3 act5-export.py
      - name: setup git config
        env:
          EMAIL: ${{ secrets.email }}
          KEY: ${{ secrets.key }}
        run: |
          git config user.name "RSS Update Bot"
          git config user.email "$EMAIL"
          git config user.signingkey "$KEY"
      - name: commit
        run: |
          git commit -a -S -m "update rss feed"
          git push
      - name: Run GitHub pages deployment
        if: success()
        uses: ./.github/workflows/pages.yml
