name: update podcast feed v3.3.0

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check py requirements
        run: |
          pip3 install -r requirements.txt
      - name: update rss feed source
        env:
          SPT_ID: ${{ secrets.spotify_client_id }}
          SPT_SC: ${{ secrets.spotify_client_secret }}
        run: |
          python3 secret.py --spotify_id "$SPT_ID" --spotify_secret "$SPT_SC"
          python3 update.py blg
      - name: merge feed source
        run: |
          python3 merge.py blg
      - name: annotate feed with various info
        run: |
          python3 annotate.py blg > blg/filter.txt
      - name: export feed into js file
        run: |
          python3 export.py blg
      - name: setup git config
        env:
          EMAIL: ${{ secrets.email }}
          KEY: ${{ secrets.key }}
        run: |
          git config user.name "RSS Update Bot"
          git config user.email "$EMAIL"
          git config user.signingkey "$KEY"
      - name: commit
        run: |
          git add -A
          git commit -S -m "update rss feed [bot action]" && git push
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [self-hosted, linux, x64]
    needs: build
    if: ${{ needs.build.result == 'success'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
