name: update podcast feed v2.0.2

on:
  schedule:
    - cron: "28 17 * * *"

jobs:
  build:
    rruns-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Running Script
        run: |
          pip install -r requirements.txt
          python act2-update.py
          python act3-merge.py
          python act4-annotate.py > filter.txt
          python act5-exportJS.py
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: checkout
          git pull origin feed
          git checkout feed
      - name: commit
        run: |
          git commit -a -m "update rss feed"
          git push origin feed
